import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'my-lib',
      formats: ['es'], // adding 'umd' requires globals set to every external module
      fileName: (format) => `react-telegram-sticker-viewer.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['react'], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          react: 'React',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
})




